name: Deploy to Heroku

on:
  push:
    branches:
      - ldy  # when push to ldy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # x86

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git identity
        run: |
          git config --global user.name "dongyul1u"
          git config --global user.email ${{ secrets.HEROKU_EMAIL_LDY }}

      # - name: Deploy client to Heroku
      #   run: |
      #     cd client
      #     docker build -t registry.heroku.com/bitcoinexplore/worker .
      #     echo ${{ secrets.HEROKU_API_KEY_LDY }} | docker login --username=_ --password-stdin registry.heroku.com
      #     docker push registry.heroku.com/bitcoinexplore/worker
      #     heroku container:release worker -a bitcoinexplore
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_LDY }}

      - name: Configure Git to use Heroku credentials
        run: |
          git config --global credential.helper store
          echo "https://heroku:${{ secrets.HEROKU_API_KEY_LDY }}@git.heroku.com" > ~/.git-credentials

      - name: Deploy mysql-api to Heroku
        run: |
          cd mysql_api

          # git config --global user.name "dongyul1u"
          # git config --global user.email ${{ secrets.HEROKU_EMAIL_LDY }}

          rm -rf .git 

          echo "target/" >> .gitignore
          echo "*.log" >> .gitignore
          echo "*.tmp" >> .gitignore
          echo "node_modules/" >> .gitignore
          echo "*.lock" >> .gitignore
          echo "*.tar.gz" >> .gitignore
          echo "*.zip" >> .gitignore
          echo "*.bin" >> .gitignore
          echo "*.iso" >> .gitignore
          echo "*.dmg" >> .gitignore
          echo ".vscode/" >> .gitignore
          echo ".idea/" >> .gitignore
          echo ".DS_Store" >> .gitignore
          echo "Thumbs.db" >> .gitignore

          git config --global user.name "dongyul1u"
          git config --global user.email ${{ secrets.HEROKU_EMAIL_LDY }}
          git init
          git checkout -b main
          git add .
          git commit -m "Deploy Rust app to Heroku"

          heroku container:login 
          # heroku buildpacks:set emk/rust -a bitcoinexploreapi
          heroku git:remote -a bitcoinexploreapi
          git push heroku main --force
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_LDY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL_LDY }}

      # - name: Deploy frontend to Heroku
      #   run: |
      #     cd WebstormProjects
      #     docker build -t registry.heroku.com/bitcoinexplorefront/web .
      #     echo ${{ secrets.HEROKU_API_KEY_LDY }} | docker login --username=_ --password-stdin registry.heroku.com
      #     docker push registry.heroku.com/bitcoinexplorefront/web
      #     heroku container:release web -a bitcoinexplorefront
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_LDY }}
