name: Deploy to Heroku

on:
  push:
    branches:
      - ldy  # when push to ldy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # x86

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        working-directory: ./client
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bitcoinexplore" #Must be unique in Heroku
          heroku_email: "${{secrets.HEROKU_EMAIL_LDY}}"
          usedocker: true