name: Deploy to Heroku

on:
  push:
    branches:
      - ldy  # when push to ldy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # x86

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy client to Heroku
        run: |
          cd client
          docker build -t registry.heroku.com/bitcoinexplore/web .
          echo ${{ secrets.HEROKU_API_KEY_LDY }} | docker login --username=_ --password-stdin registry.heroku.com
          docker push registry.heroku.com/bitcoinexplore/web
          heroku container:release web -a bitcoinexplore
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_LDY }}
          SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}