name: Deploy to Heroku

on:
  push:
    branches:
      - ldy  # when push to ldy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # x86

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy client to Heroku
        run: |
          cd client
          docker build -t registry.heroku.com/bitcoinexplore/worker .
          echo ${{ secrets.HEROKU_API_KEY_LDY }} | docker login --username=_ --password-stdin registry.heroku.com
          docker push registry.heroku.com/bitcoinexplore/worker
          heroku container:release worker -a bitcoinexplore
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_LDY }}

      - name: Deploy mysql-api to Heroku
        run: |
          cd mysql_api
          docker build -t registry.heroku.com/bitcoinexploreapi/mysql-api .
          echo ${{ secrets.HEROKU_API_KEY_LDY }} | docker login --username=_ --password-stdin registry.heroku.com
          docker push registry.heroku.com/bitcoinexploreapi/mysql-api
          heroku container:release mysql-api -a bitcoinexploreapi
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_LDY }}

      - name: Deploy frontend to Heroku
        run: |
          cd WebstormProjects
          docker build -t registry.heroku.com/bitcoinexplorefront/web .
          echo ${{ secrets.HEROKU_API_KEY_LDY }} | docker login --username=_ --password-stdin registry.heroku.com
          docker push registry.heroku.com/bitcoinexplorefront/web
          heroku container:release web -a bitcoinexplorefront
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_LDY }}